PROGRAM P32_Primer
VAR
    X2 : BOOL;
    T2 : TON;
    M110 : BOOL; (* OLD     PRIMER *)
    M111 : BOOL; (* NEW     PRIMER *)
    X3 : BOOL;
    T3 : TON;
    X1103 : BOOL; (* 현대 프라이머토출    PRIMER]  ON *)
    M102 : BOOL; (* OLD     PRIMER  ON *)
    M103 : BOOL; (* OLD     PRIMER  OFF *)
    M100 : BOOL; (* NEW     PRIMER  ON *)
    SM400 : BOOL; (* 항상on *)
    Y2D : BOOL; (* 프라이머토출 ON *)
    T10 : TON;
    Y2E : BOOL; (* 프라이머토출 OFF *)
END_VAR